### ISSUE TITLE
无法使用，一直获取不到

### ISSUE THREAD

**Issue by litteA** [SwaggyMacro/3Hours#1]
![屏幕截图 2023-12-19 231302](https://github.com/SwaggyMacro/3Hours/assets/15835570/50a545ad-a31d-4d6b-8050-988338217318)

**Comment by SwaggyMacro** [comment]
已修复，参考最新Commit 以及 Release。
操作步骤略微发生变化。
***
操作步骤：
1. 电脑登陆微信
2. 搜索打开人人3小时小程序
3. 点击小程序中 "下方导航栏→《公益机会》→《益起动》(去捐步)" 微信授权登录 
4. 双击打开本程序 等待执行完毕即可 / 或者直接在命令界面执行`python main.py`
