### ISSUE TITLE
请问按照新的操作方式还是一直获取失败怎么办？

### ISSUE THREAD

**Issue by ledeyi** [SwaggyMacro/3Hours#2]
<img width="869" alt="屏幕截图 2024-07-30 132952" src="https://github.com/user-attachments/assets/b4c14577-a3e2-41c6-b825-60708b906e46">

**Comment by SwaggyMacro** [comment]
这个是AI回复那段出问题了，信息都是正常获取到了

**Comment by ledeyi** [comment]
谢谢大佬回答，那我应该怎么解决这个问题呢？我尝试过科学上网但并没有起到作用。

**Comment by ledeyi** [comment]
谢谢大佬回答，那我应该怎么解决这个问题呢？我尝试过科学上网但并没有起到作用。

**Comment by ledeyi** [comment]
<img width="1118" alt="屏幕截图 2024-07-30 191849" src="https://github.com/user-attachments/assets/5bf0024a-59a1-4f8c-acd2-a9a9851f43c4">
并且我注意到脚本读取到的问题和微信小程序上的问题不一致，请问这是正常的吗？

**Comment by ledeyi** [comment]
> 这个是AI回复那段出问题了，信息都是正常获取到了

谢谢大佬回答，那我应该怎么解决这个问题呢？我尝试过科学上网但并没有起到作用。

**Comment by SwaggyMacro** [comment]
> <img alt="屏幕截图 2024-07-30 191849" width="1118" src="https://private-user-images.githubusercontent.com/176984619/353436692-5bf0024a-59a1-4f8c-acd2-a9a9851f43c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzODk3NTYsIm5iZiI6MTcyMjM4OTQ1NiwicGF0aCI6Ii8xNzY5ODQ2MTkvMzUzNDM2NjkyLTViZjAwMjRhLTU5YTEtNGY4Yy1hY2QyLWE5YTk4NTFmNDNjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwMTMwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDFjNmQ0YzUwZjMxMDRkMDY5NmMxNzZkMzk3OTdmOWEwYjI2OWEwNDU5OGE0MDljNjlmZjA1NmRlZGM3NjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Dcx3uCXurbGfeXg-Er_OaEfECJaD7YAEc5mfZamlgiU"> 并且我注意到脚本读取到的问题和微信小程序上的问题不一致，请问这是正常的吗？

正常的，脚本是直接把所有问题读出来的，小程序上面只显示部分题目。

**Comment by SwaggyMacro** [comment]
> > 这个是AI回复那段出问题了，信息都是正常获取到了
> 
> 谢谢大佬回答，那我应该怎么解决这个问题呢？我尝试过科学上网但并没有起到作用。

你有使用AI吗？回答问题的功能需要接入AI

**Comment by SwaggyMacro** [comment]
如果没有OpenAI的API Key的话可以去网上找找免费Key，或者参考该项目[github.com/chatanywhere/GPT_API_free](https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file#%E5%85%8D%E8%B4%B9%E4%BD%BF%E7%94%A8)申请免费API KEY ，另外调用OPENAI需要代理。

**Comment by SwaggyMacro** [comment]
> 如果没有OpenAI的API Key的话可以去网上找找免费Key，或者参考该项目[github.com/chatanywhere/GPT_API_free](https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file#%E5%85%8D%E8%B4%B9%E4%BD%BF%E7%94%A8)申请免费API KEY ，另外调用OPENAI需要代理。
