### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by kkone1-key** [SwaggyMacro/3Hours#4]
出问题了，跑不了，求大佬解答，我应该怎么做
![9be9fd2f1962f81e0024be308bd3d3d](https://github.com/user-attachments/assets/bb5aeaad-29fa-41c5-a248-4fd4c9f25c3f)

**Comment by SwaggyMacro** [comment]
修改`main.py`第`36`以及`42`行，修改为固定回答， answer = "xxxxx回答"，或者配置OpenAI 使用AI回答。
![image](https://github.com/user-attachments/assets/078aee00-9ff8-4ce7-a033-8afb042b0988)
